version: '3.8'

services:
  web:
    build: .
    ports:
      - "5001:5000"
    environment:
      - FLASK_APP=wsgi.py
      - FLASK_DEBUG=1
      - SECRET_KEY=dev-key
      - ENCRYPTION_KEY=dev-key
      - FLASK_LOG_LEVEL=DEBUG
      - SQLALCHEMY_DATABASE_URI=postgresql://onetimeshare:secret@db:5432/onetimeshare
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./instance:/app/instance
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=onetimeshare
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=onetimeshare
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U onetimeshare"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  postgres_data: 