apiVersion: v1
kind: Secret
metadata:
  name: {{ include "onetimeshare.fullname" . }}
  labels:
    {{- include "onetimeshare.labels" . | nindent 4 }}
type: Opaque
data:
  secret-key: {{ .Values.secrets.secretKey | b64enc | quote }}
  encryption-key: {{ .Values.secrets.encryptionKey | b64enc | quote }} 