apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "onetimeshare.serviceAccountName" . }}
  labels:
    {{- include "onetimeshare.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }} 